title: "Recursive Learning"
baseurl: "/clients"
url: "https://recursivelearning.app"
markdown: kramdown
theme: minima

include:
  - _includes       # Include the _includes directory
  - clients         # Include the clients directory
  - assets          # Include the assets directory if needed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# (Comment out or leave out the permalink if not ready to use)
# permalink: "/:categories/:title.html"

plugins:
  - jekyll-feed
  # Add other plugins here if needed

destination: "_site"
