title: "Recursive Learning"
baseurl: ""             # Deploying at domain root
url: "https://recursivelearning.app"
markdown: kramdown
theme: minima

# This pattern means: "/:categories/:title.html"
# If a page has categories: [bhb], it becomes "/bhb/PAGE-TITLE.html"
# If categories: [elpl], it becomes "/elpl/PAGE-TITLE.html", etc.
permalink: "/:categories/:title.html"

include:
  - clients
  - shared_jekyll

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed
